---
- hosts: all
  tasks:
    - name: make file
      synchronize:
        src: /3dd/Raid/backup_data/rnd/tools/scripts/root
        dest: /var/spool/cron/root
        owner: root
        group: root
        mode: 0644