---
- hosts: all
  tasks:
    - name: Install maya2018
      yum: name=Maya2018_64
      state: latest

    - name: Install adlmapps14
      yum: name=adlmapps14
      state: latest

    - name: Install adlmflexnetclient
      yum: name=adlmflexnetclient
      state: latest

    - name: license for maya2018
      copy:
        src: /var/opt/Autodesk/Adlm/ASR
        dest: /var/opt/Autodesk/Adlm/ASR
        owner: root
        group: root
        mode: 0755
        directory_mode: yes

    - name: license for maya2018_0.1
      copy:
        src: /var/opt/Autodesk/Adlm/.config
        dest: /var/opt/Autodesk/Adlm/.config
        owner: root
        group: root
        mode: 0755
        directory_mode: yes
