---
- hosts: all
  tasks:
    - name: Install maya2018
      yum: name=Maya2018_64
      state: latest

    - name: Install adlmapps14
      yum: name=adlmapps14
      state: latest

    - name: Install adlmflexnetclient
      yum: name=adlmflexnetclient
      state: latest

    - name: license for maya2018
      synchronize:
        src: /3dd/Raid/Kollection/Soft/tools/Adlm/.config/
        dest: /var/opt/Autodesk/Adlm/.config/
        #owner: root
        #group: root
        #mode: 0644
        #remote_src: yes
    #- name: license for maya2018_0.1
      #copy:
      #  src: 
      #  dest: /var/opt/Autodesk/Adlm/.config
      #  owner: root
      #  group: root
      #  mode: 0755
      #  directory_mode: yes
      #  remote_src: yes