---
- hosts: all
  tasks:
    - name: Install nfs-utils
      yum: name=nfs-utils 
      state: latest

    - name: Install nfs-utils-lib
      yum: name=nfs-utils-lib
      state: latest

    - name: install puppet repo
      yum:
        name: https://yum.puppetlabs.com/puppetlabs-release-el-7.noarch.rpm
        state: present
        
    - name: Install puppet
      yum: name=puppet
      state: latest