---
- hosts: all
  tasks:
    - name: puppet enable auto start
      command: systemctl enable puppet
      
    - name: maya2016_install
      command: maya2016_install
      
    - name: firewall stop
      command: systemctl stop firewalld
      
    - name: firewall disable
      command: systemctl disable firewalld

    - name: docker_install
      command: docker_install_el7

    - name: docker_licence
      command: docker_pixar_license_server_container_with_new_license_install